/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MuxFrame.java
 *
 * Created on Sep 8, 2010, 4:21:47 PM
 */

package vbs2gui.video;

import java.awt.Color;

/**
 *
 * @author nbb
 */
public class MuxFrame extends javax.swing.JFrame {

    /** Creates new form MuxFrame */
    public MuxFrame(String title) {
        setTitle(title);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        posXLabel = new javax.swing.JLabel();
        posXField = new javax.swing.JTextField();
        posYLabel = new javax.swing.JLabel();
        posYField = new javax.swing.JTextField();
        posZLabel = new javax.swing.JLabel();
        posZField = new javax.swing.JTextField();
        uavPanel = new javax.swing.JPanel();
        dirZField = new javax.swing.JTextField();
        dirYField = new javax.swing.JTextField();
        dirXField = new javax.swing.JTextField();
        dirXLabel = new javax.swing.JLabel();
        dirYLabel = new javax.swing.JLabel();
        dirZLabel = new javax.swing.JLabel();
        upZField = new javax.swing.JTextField();
        upYField = new javax.swing.JTextField();
        upXField = new javax.swing.JTextField();
        upXLabel = new javax.swing.JLabel();
        upYLabel = new javax.swing.JLabel();
        upZLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        posXLabel.setText("pos X (m)");

        posYLabel.setText("pos Y (m)");

        posZLabel.setText("pos ASL (m)");

        javax.swing.GroupLayout uavPanelLayout = new javax.swing.GroupLayout(uavPanel);
        uavPanel.setLayout(uavPanelLayout);
        uavPanelLayout.setHorizontalGroup(
            uavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );
        uavPanelLayout.setVerticalGroup(
            uavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        dirXLabel.setText("dir X");

        dirYLabel.setText("dir Y");

        dirZLabel.setText("dir Z");

        upXLabel.setText("up X");

        upYLabel.setText("up Y");

        upZLabel.setText("up Z");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uavPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posXLabel)
                            .addComponent(posYLabel)
                            .addComponent(posZLabel)
                            .addComponent(dirXLabel)
                            .addComponent(dirYLabel)
                            .addComponent(dirZLabel)
                            .addComponent(upXLabel)
                            .addComponent(upYLabel)
                            .addComponent(upZLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upZField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upYField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upXField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dirZField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dirYField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dirXField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(posXField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(posYField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(posZField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posXLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(posXField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posYLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(posYField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posZLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(posZField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirXLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(dirXField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirYLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(dirYField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirZLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(dirZField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upXLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(upXField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upYLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(upYField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upZLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(upZField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uavPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuxFrame("").setVisible(true);
            }
        });
    }

    public void update(int sRGB, double[] telemetry) {
        uavPanel.setBackground(new Color(sRGB));
        posXField.setText(telemetry[0] + "");
        posYField.setText(telemetry[1] + "");
        posZField.setText(telemetry[2] + "");
        dirXField.setText(telemetry[3] + "");
        dirYField.setText(telemetry[4] + "");
        dirZField.setText(telemetry[5] + "");
        upXField.setText(telemetry[6] + "");
        upYField.setText(telemetry[7] + "");
        upZField.setText(telemetry[8] + "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dirXField;
    private javax.swing.JLabel dirXLabel;
    private javax.swing.JTextField dirYField;
    private javax.swing.JLabel dirYLabel;
    private javax.swing.JTextField dirZField;
    private javax.swing.JLabel dirZLabel;
    private javax.swing.JTextField posXField;
    private javax.swing.JLabel posXLabel;
    private javax.swing.JTextField posYField;
    private javax.swing.JLabel posYLabel;
    private javax.swing.JTextField posZField;
    private javax.swing.JLabel posZLabel;
    private javax.swing.JPanel uavPanel;
    private javax.swing.JTextField upXField;
    private javax.swing.JLabel upXLabel;
    private javax.swing.JTextField upYField;
    private javax.swing.JLabel upYLabel;
    private javax.swing.JTextField upZField;
    private javax.swing.JLabel upZLabel;
    // End of variables declaration//GEN-END:variables

}
