cd F:\laptop\owens\

SET PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files\CommonFiles\Adaptec Shared\System;C:\PROGRA~1\IBM\AFS\Common;C:\PROGRA~1\CMU\KClient\bin32;;F:\Program Files\MATLAB704\bin\win32;;C:\Program Files\Common Files\GTK\2.0\bin;C:\Program Files\OpenAFS\Common;C:\Program Files\OpenAFS\Client\Program;F:\Program Files\Jahshaka\..\gtk2\bin;F:\Program Files\Jahshaka\..\mlt\bin;C:\Program Files\MIT\Kerberos\bin;F:\Program Files\OpenLibraries\bin;F:\Program Files\Smart Projects\IsoBuster;C:\Program Files\Microsoft SQL Server\80\Tools\Binn\;C:\Program Files\QuickTime\QTSystem\;C:\utils\;C:\utils\bin\;F:\Program Files\OpenCV\bin;C:\laptop\owens\j3d\lib\i386

REM "c:\Program Files\Java\jdk1.6.0_10\bin\java" -Xmx1024M -Djava.library.path=f:\laptop\owens\jogl-1.1.1-windows-i586\lib -cp .;f:\laptop\owens\jogl-1.1.1-windows-i586\lib\jogl.jar;f:\laptop\owens\jogl-1.1.1-windows-i586\lib\gluegen-rt.jar;F:\laptop\owens\jai\jai_codec.jar;F:\laptop\owens\jai\jai_core.jar;F:\laptop\owens\geotransform\geotransform.jar;F:\laptop\owens;F:\laptop\owens\j3d\lib\ext\j3dcore.jar;F:\laptop\owens\j3d\lib\ext\j3dutils.jar;F:\laptop\owens\j3d\lib\ext\vecmath.jar suave.Main --dem f:\laptop\owens\gascola_data\GascolaBareEarth1m.tif --texture f:\laptop\owens\gascola_data\gascola_mosaic_g1024_1024.jpg --sky f:\laptop\owens\generictextures\sky-texture-03_ogc_256_256.jpg --ground f:\laptop\owens\generictextures\earth_texture_3131.jpg --uavlog f:\laptop\owens\suave\gascola2.log --skyfront F:\laptop\owens\sky\sky12\frontax2.jpg --skyback F:\laptop\owens\sky\sky12\backax2.jpg --skyleft F:\laptop\owens\sky\sky12\leftax2.jpg --skyright F:\laptop\owens\sky\sky12\rightax2.jpg --skytop F:\laptop\owens\sky\sky12\topax2.jpg
REM "c:\Program Files\Java\jdk1.6.0_10\bin\java" -Xmx1024M -Djava.library.path=f:\laptop\owens\jogl-1.1.1-windows-i586\lib -cp .;f:\laptop\owens\jogl-1.1.1-windows-i586\lib\jogl.jar;f:\laptop\owens\jogl-1.1.1-windows-i586\lib\gluegen-rt.jar;F:\laptop\owens\jai\jai_codec.jar;F:\laptop\owens\jai\jai_core.jar;F:\laptop\owens\geotransform\geotransform.jar;F:\laptop\owens;F:\laptop\owens\objloader\OBJLoader.jar suave.Main --dem f:\laptop\owens\gascola_data\GascolaBareEarth1m.tif --texture f:\laptop\owens\generictextures\earth_texture_3131.jpg --sky f:\laptop\owens\generictextures\sky-texture-03_ogc_256_256.jpg --ground f:\laptop\owens\generictextures\earth_texture_3131.jpg --uavlog f:\laptop\owens\suave\gascola3.log --skyfront F:\laptop\owens\sky\sky12\frontax2.jpg --skyback F:\laptop\owens\sky\sky12\backax2.jpg --skyleft F:\laptop\owens\sky\sky12\leftax2.jpg --skyright F:\laptop\owens\sky\sky12\rightax2.jpg --skytop F:\laptop\owens\sky\sky12\topax2.jpg --uavmodel procerus_complete

"c:\Program Files\Java\jdk1.6.0_10\bin\java" -XX:+UseParallelGC -Xmx1024M -Djava.library.path=f:\laptop\owens\jogl-1.1.1-windows-i586\lib -cp .;f:\laptop\owens\jogl-1.1.1-windows-i586\lib\jogl.jar;f:\laptop\owens\jogl-1.1.1-windows-i586\lib\gluegen-rt.jar;F:\laptop\owens\jai\jai_codec.jar;F:\laptop\owens\jai\jai_core.jar;F:\laptop\owens\geotransform\geotransform.jar;F:\laptop\owens;F:\laptop\owens\objloader\OBJLoader.jar;F:\laptop\owens\jogl-demos-src\jogl-demos\src\ suave.Main --dem f:\laptop\owens\gascola_data\GascolaBareEarth1m.tif --texture f:\laptop\owens\gascola_data\gascola_mosaic_g1024_1024.jpg --sky f:\laptop\owens\generictextures\sky-texture-03_ogc_256_256.jpg --ground f:\laptop\owens\generictextures\earth_texture_3131.jpg --uavlog f:\laptop\owens\suave\gascola3.log --skyfront F:\laptop\owens\sky\sky12\frontax2.jpg --skyback F:\laptop\owens\sky\sky12\backax2.jpg --skyleft F:\laptop\owens\sky\sky12\leftax2.jpg --skyright F:\laptop\owens\sky\sky12\rightax2.jpg --skytop F:\laptop\owens\sky\sky12\topax2.jpg --uavmodel procerus_complete --paintImage f:\laptop\owens\suave\00021421.png --videoframe f:\laptop\owens\suave\video21421.txt  --meshstep 25 --vclogstartat 6000000 --vclog F:\laptop\owens\suave\telemetry_UAV5_2008_10_22_00.m --imagedir g:\suave_2008_10_22_30minutes_split

REM --loadserialdemAndTexture F:\laptop\owens\gascola_data\serialized_dem_and_texture.ser

REM "c:\Program Files\Java\jdk1.6.0_10\bin\java" -Xmx1024M -Djava.library.path=f:\laptop\owens\jogl-1.1.1-windows-i586\lib -cp .;f:\laptop\owens\jogl-1.1.1-windows-i586\lib\jogl.jar;f:\laptop\owens\jogl-1.1.1-windows-i586\lib\gluegen-rt.jar;F:\laptop\owens\jai\jai_codec.jar;F:\laptop\owens\jai\jai_core.jar;F:\laptop\owens\geotransform\geotransform.jar;F:\laptop\owens;F:\laptop\owens\objloader\OBJLoader.jar suave.Main --dem f:\laptop\owens\gascola_data\GascolaBareEarth1m.tif --texture f:\laptop\owens\gascola_data\gascola_mosaic_g1024_1024.jpg --sky f:\laptop\owens\generictextures\sky-texture-03_ogc_256_256.jpg --ground f:\laptop\owens\generictextures\earth_texture_3131.jpg --uavlog f:\laptop\owens\suave\gascola3.log --skyfront F:\laptop\owens\sky\sky12\frontax2.jpg --skyback F:\laptop\owens\sky\sky12\backax2.jpg --skyleft F:\laptop\owens\sky\sky12\leftax2.jpg --skyright F:\laptop\owens\sky\sky12\rightax2.jpg --skytop F:\laptop\owens\sky\sky12\topax2.jpg --uavmodel procerus_complete


cd f:\laptop\owens\suave
