cd C:\laptop\owens\

set PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files\ATI Technologies\ATI Control Panel;C:\Program Files\MIT\Kerberos\bin;C:\Program Files\OpenAFS\Common;C:\Program Files\OpenAFS\Client\Program;C:\Program Files\Java\jdk1.6.0_01\bin;C:\Program Files\QuickTime\QTSystem\;C:\laptop\owens\j3d\lib\i386

REM "c:\Program Files\Java\jdk1.6.0_07\bin\java" -Xmx1024M -Djava.library.path=c:\laptop\owens\jogl-1.1.1-windows-i586\lib -cp .;c:\laptop\owens\jogl-1.1.1-windows-i586\lib\jogl.jar;c:\laptop\owens\jogl-1.1.1-windows-i586\lib\gluegen-rt.jar;C:\laptop\owens\jai\jai_codec.jar;C:\laptop\owens\jai\jai_core.jar;C:\laptop\owens\geotransform\geotransform.jar;C:\laptop\owens;C:\laptop\owens\j3d\lib\ext\j3dcore.jar;C:\laptop\owens\j3d\lib\ext\j3dutils.jar;C:\laptop\owens\j3d\lib\ext\vecmath.jar suave.Main --dem c:\laptop\owens\gascola_data\GascolaBareEarth1m.tif --texture c:\laptop\owens\gascola_data\gascola_mosaic_g1024_1024.jpg --sky c:\laptop\owens\generictextures\sky-texture-03_ogc_256_256.jpg --ground c:\laptop\owens\generictextures\earth_texture_3131.jpg --uavlog c:\laptop\owens\suave\gascola2.log --skyfront C:\laptop\owens\sky\sky12\frontax2.jpg --skyback C:\laptop\owens\sky\sky12\backax2.jpg --skyleft C:\laptop\owens\sky\sky12\leftax2.jpg --skyright C:\laptop\owens\sky\sky12\rightax2.jpg --skytop C:\laptop\owens\sky\sky12\topax2.jpg
REM "c:\Program Files\Java\jdk1.6.0_07\bin\java" -Xmx1024M -Djava.library.path=c:\laptop\owens\jogl-1.1.1-windows-i586\lib -cp .;c:\laptop\owens\jogl-1.1.1-windows-i586\lib\jogl.jar;c:\laptop\owens\jogl-1.1.1-windows-i586\lib\gluegen-rt.jar;C:\laptop\owens\jai\jai_codec.jar;C:\laptop\owens\jai\jai_core.jar;C:\laptop\owens\geotransform\geotransform.jar;C:\laptop\owens;C:\laptop\owens\objloader\OBJLoader.jar suave.Main --dem c:\laptop\owens\gascola_data\GascolaBareEarth1m.tif --texture c:\laptop\owens\generictextures\earth_texture_3131.jpg --sky c:\laptop\owens\generictextures\sky-texture-03_ogc_256_256.jpg --ground c:\laptop\owens\generictextures\earth_texture_3131.jpg --uavlog c:\laptop\owens\suave\gascola3.log --skyfront C:\laptop\owens\sky\sky12\frontax2.jpg --skyback C:\laptop\owens\sky\sky12\backax2.jpg --skyleft C:\laptop\owens\sky\sky12\leftax2.jpg --skyright C:\laptop\owens\sky\sky12\rightax2.jpg --skytop C:\laptop\owens\sky\sky12\topax2.jpg --uavmodel procerus_complete

"c:\Program Files\Java\jdk1.6.0_07\bin\java" -Xmx1024M -Djava.library.path=c:\laptop\owens\jogl-1.1.1-windows-i586\lib -cp .;c:\laptop\owens\jogl-1.1.1-windows-i586\lib\jogl.jar;c:\laptop\owens\jogl-1.1.1-windows-i586\lib\gluegen-rt.jar;C:\laptop\owens\jai\jai_codec.jar;C:\laptop\owens\jai\jai_core.jar;C:\laptop\owens\geotransform\geotransform.jar;C:\laptop\owens;C:\laptop\owens\objloader\OBJLoader.jar;c:\laptop\owens\jogl-demos-src\jogl-demos\src\ suave.HWShadowmapsSimple


cd c:\laptop\owens\suave
